### PR TITLE
Added API for cloud rendering

### PR DESCRIPTION
**Pull request by Takkkom**

### CODE REVIEW

**Comment by Takkkom** [comment]
I have read and hereby affirm the entire contents of the Developer Certificate of Origin.

**Review by embeddedt — COMMENTED** [review]
I would design a more standard event for this one. Just pass the distance in and allow mods to alter it dynamically with a setter/getter. I would also rename it to something simpler like `ModifyCloudRenderDistanceEvent`.

Judging by the code, I'm guessing you based the design off the event I added for controlling chunk render distance. The holder/filter function pattern was only needed there because that code path is extremely hot and I needed to guarantee the JVM would be able to optimize it correctly. Here, the event is only going to fire once per frame, and performance is nowhere near as much of a concern. We do not need to require a mod to register its own function that gets stored in a constant.

Aside from that I have no problems adding such an event.

**Comment by embeddedt** [comment]
Thanks, I merged this manually with some tweaks (I wanted to use a proper event, and realized afterward it would also make sense to design it to allow adding more context later).

It was nice of you to not even wait for this to be merged and immediately [add more hacks in an add-on to bypass the mixin restriction](https://github.com/dima-dencep/rubidium-extra/commit/a26e4c6bdb9f7bfd8e5e3e58be6cd6d74e593fa6), though... :confused: This doesn't feel like a very collaborative move.

**Comment by dima-dencep** [comment]
If you're interested, this hack is now in NanoLiveConfig

**Pull request closed without merging**
