### PR TITLE
Copy my changes from Rubidium PRs

### PR DESCRIPTION
**Pull request by Kasualix**
Migrated from [there](https://github.com/Asek3/Rubidium/pulls). 

Includes the [RenderTypeCache](https://legacy.curseforge.com/minecraft/mc-mods/rendertypecache)'s mixin (I'm quite sure Embeddium should directly include this patch, as for why in Rubidium's PR I only cache this list, it's because when I made the PR there, I didn't realize it could be done this way XD). 

The rest is just updating the Arch Loom version, Forge version, and the value in pack.mcmeta.

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]
Approved. I will pull the changes manually, as I'd like them in separate commits and the whitespace changes will confuse Git when I merge to 1.18 and above.

**Comment by Kasualix** [comment]
How about the performFluidDisplayTick method patch?

**Comment by embeddedt** [comment]
I'm nervous about whether the solution is correct for it - presumably there was a good reason upstream didn't remove the allocation at the time. Does it make any difference to FPS or is it just a theoretical improvement?

**Comment by Kasualix** [comment]
just theoretically

**Comment by Kasualix** [comment]
>presumably there was a good reason upstream didn't remove the allocation at the time. 

Perhaps it would be better to go and ask Jelly directly.

**Comment by Kasualix** [comment]
https://discord.com/channels/602796788608401408/754753337525534892/1147822769300570173
How about this?

**Comment by embeddedt** [comment]
I wasn't really worried about restoring the Y position of the mutable BlockPos, since `performFluidDisplayTick` is the last function that uses it anyways. I was just concerned about the ramifications of providing a mutable object when adding the particles instead of an immutable one. It's probably harmless, but I like to avoid changing code that works unless it's causing issues (whether a bug or lag).

**Pull request closed without merging**
