### PR TITLE
Add Japanese

### PR DESCRIPTION
**Pull request by u7f8au7fbd**
Some technical terms cannot be translated into Japanese and include redundant translations. Please forgive us.

### CODE REVIEW

**Comment by embeddedt** [comment]
Thanks for your effort here! Embeddium and Sodium should be sharing the same translation strings, so I think using the unofficial [Translations for Sodium](https://legacy.curseforge.com/minecraft/texture-packs/translations-for-sodium) resource pack would be a better solution than maintaining an independent copy in Embeddium. What do you think?

**Comment by u7f8au7fbd** [comment]
Are all the texts used in  Embeddium the same as those in Sodium?

**Comment by embeddedt** [comment]
They should be; I don't see any reason why the UI code should have been changed (unless Rubidium changed something I'm unaware of).

**Comment by u7f8au7fbd** [comment]
OK.... What I did this time was unnecessary.

**Comment by embeddedt** [comment]
It's okay! The translations resource pack is not that well-known.

**Pull request closed without merging**
