### PR TITLE
Update mod icon

### PR DESCRIPTION
**Pull request by input-Here**
Does what it says on the tin, changes the mod icon to match Sodium's icon style.
I just made this as an alternative option to have, I don't mind if it doesn't get used :)

### CODE REVIEW

**Comment by input-Here** [comment]
If anyone's interested or needs it, the svg file can be found [here](https://file.garden/ZTOmwnryMijlVX30/embeddium4.svg)

**Comment by embeddedt** [comment]
Thanks! After some discussion and tweaks in the Discord I've committed a very slightly modified version here: https://github.com/embeddedt/embeddium/commit/7477ba6d1414330c76cf0d0f1c48c0b35752360f

(The only difference is a small tweak to the curvature at the bottom.)

**Comment by input-Here** [comment]
Sure! I also took a look at the modified one you committed, and it has some problems (it's inconsistently curved and misaligned from the pixel grid), so I made a version that fixes these ([svg](https://file.garden/ZTOmwnryMijlVX30/embeddium/icon.svg), png). Would it be easier if I open a PR or for you to commit these directly?

**Comment by embeddedt** [comment]
I honestly couldn't tell the difference until flipping between them, but yes, yours looks sharper. Please open a PR and I'll merge it.

**Comment by input-Here** [comment]
PR opened

**Pull request closed without merging**
